Port libedit from termcap to terminfo.

diff --git a/trunk/devroot/configure b/trunk/devroot/configure
--- a/trunk/devroot/configure
+++ b/trunk/devroot/configure
@@ -1859,24 +1859,24 @@ mkdir -p $objdir/test
 
 
 if test "x$build_libedit" = "xyes" ; then
-  echo $ac_n "checking for tgetent in -ltermcap""... $ac_c" 1>&6
-echo "configure:1864: checking for tgetent in -ltermcap" >&5
-ac_lib_var=`echo termcap'_'tgetent | sed 'y%./+-%__p_%'`
+  echo $ac_n "checking for tigetstr in -lcurses""... $ac_c" 1>&6
+echo "configure:1864: checking for tigetstr in -lcurses" >&5
+ac_lib_var=`echo curses'_'tigetstr | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   ac_save_LIBS="$LIBS"
-LIBS="-ltermcap  $LIBS"
+LIBS="-lcurses  $LIBS"
 cat > conftest.$ac_ext <<EOF
 #line 1872 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
     builtin and then its argument prototype would still apply.  */
-char tgetent();
+char tigetstr();
 
 int main() {
-tgetent()
+tigetstr()
 ; return 0; }
 EOF
 if { (eval echo configure:1883: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
@@ -1898,7 +1898,7 @@ if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
 else
   echo "$ac_t""no" 1>&6
 \
-    { echo "configure: error: Cannot find the termcap library" 1>&2; exit 1; }
+    { echo "configure: error: Cannot find the curses library" 1>&2; exit 1; }
 fi
 
 fi
